from abc import ABC, abstractmethod
from os import environ
from logging import getLogger
from requests import post

import json
from typing import List
from .util import encode_values, encode_function_call

LOGGER = getLogger(__name__)

DEFAULT_ROLLUP_URL = 'http://127.0.0.1:5004'

def encode(d):
    return "0x" + d.encode("utf-8").hex()

class Output(ABC):
    """
    Base class representing a result generated by processing an input.

    It is resposible for converting its payload to the format expected by
    Cartesi rollups.

        Parameters:
            payload(str): the actual data generated after processing the input
    """

    def __init__(self, payload: str, address: str = None):
        self.endpoint = "/output"
        if payload[:2] == "0x":
            self.payload = payload
        else:
            self.payload = "0x" + payload

        if address is None:
            address = environ.get(
                'ROLLUP_HTTP_SERVER_URL',
                DEFAULT_ROLLUP_URL
            )
        self.address = address  
    
    @classmethod
    def from_hex(cls, hex_value:str):
        return cls(hex_value)

    def create(self, rollup_server_address=None):
        rollup_server = self.address
        if rollup_server_address is not None:
            rollup_server = rollup_server_address

        return post(rollup_server + self.endpoint, json={"payload": self.payload})

class Voucher(Output):
    """
    A Voucher is an `Output` representing a transaction
    that can be carried out on the base layer blockchain,
    such as a transfer of assets.

        Parameters:
            destination(str): destination of the contract who will execute the payload
            payload(bytes): an ABI encoded contract function call
    """

    def __init__(self, destination: str, payload: bytes|str, value = None, address: str = None):
        self.endpoint = "/voucher"
        self.destination = destination
        self.value = value

        if value is None:
            self.value = '0x' + encode_values(["uint256"], [0]).hex()

        if payload[:2] == "0x":
            super().__init__(payload, address=address)
        else:        
            hexpayload = "0x" + payload.hex()
            super().__init__(hexpayload, address=address)
    
    @classmethod
    def from_hex(cls, destination:str, hex_value:str, value:int=None):
        return cls(destination, hex_value, value)

    @classmethod
    def from_function_selector(cls, destination:str, selector:str, types:List[str], values:List[int]):
        transfer_payload = encode_function_call(selector, types, values)
        return cls(destination, transfer_payload)

    def create(self, rollup_server_address=None):
        rollup_server = self.address

        if rollup_server_address is not None:
            rollup_server = rollup_server_address

        return post(rollup_server + "/voucher", json={"payload": self.payload, "destination": self.destination, "value": self.value})

class Notice(Output):
    """
    A Notice is an `Output` representing an informational statement
    that can be validated in the base layer blockchain.

        Parameters:
            payload(str): a string containing arbitrary data
    """

    def __init__(self, payload: str):
        super().__init__(payload)
        self.endpoint = "/notice"

    @classmethod
    def from_json(cls, json_object):
        if (isinstance(json_object, str)):
            return cls.from_string(json_object)
        
        j_string = json.dumps(json_object)
        return cls.from_string(j_string)
    
    @classmethod
    def from_string(cls, string:str):
        hex_encoded = encode(string)
        return cls(hex_encoded)

class Report(Output):
    """
    A Report is an `Output` representing an application log.

        Parameters:
            payload(str): a string containing arbitrary data
    """

    def __init__(self, payload: str):
        super().__init__(payload)
        self.endpoint = "/report"

    @classmethod
    def from_json(cls, json_object):
        if (isinstance(json_object, str)):
            return cls.from_string(json_object)
        
        j_string = json.dumps(json_object)
        return cls.from_string(j_string)
    
    @classmethod
    def from_string(cls, string:str):
        hex_encoded = encode(string)
        return cls(hex_encoded)